In [4]:
import numpy as np
import pandas as pd

DataFrame = pd.read_csv('admission.csv', delimiter=';')
#Base de dados independentes
X = DataFrame.iloc[:, :-1].values
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
imputer = imputer.fit_transform(X[:,1:])

In [5]:
#Base de dados dependentes
Y = DataFrame.iloc[:,-1].values

# Transformar nomes em números (LabelEncoder)
from sklearn.preprocessing import LabelEncoder

label_Encoder_X = LabelEncoder()
X[:, 0] = label_Encoder_X.fit_transform(X[:, 0])

print(X)

[[6 337 118 4 4.5 4.5 9.65 1]
 [0 324 107 4 4.0 4.5 8.87 1]
 [5 316 104 3 3.0 3.5 8.0 1]
 [1 322 110 3 3.5 2.5 8.67 1]
 [8 314 103 2 2.0 3.0 8.21 0]
 [4 330 115 5 4.5 3.0 9.34 1]
 [3 321 109 3 3.0 4.0 8.2 1]
 [2 308 101 2 3.0 4.0 7.9 0]
 [7 302 102 1 2.0 1.5 8.0 0]]


In [6]:
#Jogar coluna fora
X = X[:, 1:]
#One hot encoding
D = pd.get_dummies(X[:, 0])
X = np.insert(X, 0, D.values, axis=1)

In [7]:
print(X)

[[False False False False False False False False True 337 118 4 4.5 4.5
  9.65 1]
 [False False False False False False False True False 324 107 4 4.0 4.5
  8.87 1]
 [False False False False True False False False False 316 104 3 3.0 3.5
  8.0 1]
 [False False True False False False False False False 322 110 3 3.5 2.5
  8.67 1]
 [False False False False False False True False False 314 103 2 2.0 3.0
  8.21 0]
 [False False False True False False False False False 330 115 5 4.5 3.0
  9.34 1]
 [False True False False False False False False False 321 109 3 3.0 4.0
  8.2 1]
 [False False False False False True False False False 308 101 2 3.0 4.0
  7.9 0]
 [True False False False False False False False False 302 102 1 2.0 1.5
  8.0 0]]


In [8]:
from sklearn.model_selection import  train_test_split
X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, test_size = 0.2)

# Valores entre 10% e 20% é o padrão

In [9]:
print(X_Train)

[[False False False False True False False False False 316 104 3 3.0 3.5
  8.0 1]
 [False False False False False False False False True 337 118 4 4.5 4.5
  9.65 1]
 [False False True False False False False False False 322 110 3 3.5 2.5
  8.67 1]
 [False True False False False False False False False 321 109 3 3.0 4.0
  8.2 1]
 [False False False False False False False True False 324 107 4 4.0 4.5
  8.87 1]
 [True False False False False False False False False 302 102 1 2.0 1.5
  8.0 0]
 [False False False True False False False False False 330 115 5 4.5 3.0
  9.34 1]]


Computando normalização de dados....

In [10]:
from sklearn.preprocessing import StandardScaler
scale_X = StandardScaler()
X_Train = scale_X.fit_transform(X_Train)
X_Test = scale_X.fit_transform(X_Test)

In [11]:
print(X_Train)

[[-0.40824829 -0.40824829 -0.40824829 -0.40824829  2.44948974  0.
   0.         -0.40824829 -0.40824829 -0.55978285 -1.00036543 -0.24618298
  -0.59160798  0.1393466  -1.11566534  0.40824829]
 [-0.40824829 -0.40824829 -0.40824829 -0.40824829 -0.40824829  0.
   0.         -0.40824829  2.44948974  1.49741911  1.64925111  0.61545745
   1.18321596  1.11477282  1.60863374  0.40824829]
 [-0.40824829 -0.40824829  2.44948974 -0.40824829 -0.40824829  0.
   0.         -0.40824829 -0.40824829  0.02798914  0.13518452 -0.24618298
   0.         -0.83607962 -0.0094348   0.40824829]
 [-0.40824829  2.44948974 -0.40824829 -0.40824829 -0.40824829  0.
   0.         -0.40824829 -0.40824829 -0.06997286 -0.05407381 -0.24618298
  -0.59160798  0.62705971 -0.78544727  0.40824829]
 [-0.40824829 -0.40824829 -0.40824829 -0.40824829 -0.40824829  0.
   0.          2.44948974 -0.40824829  0.22391314 -0.43259046  0.61545745
   0.59160798  1.11477282  0.32078327  0.40824829]
 [ 2.44948974 -0.40824829 -0.40824829 -0.4082